name:                ASE
version:             0.1.0.0
github:              "N0822325/Haskell-Tax-Calculator"
license:             BSD3
author:              "Bradley Smith"
maintainer:          "N0822325@my.ntu.ac.uk"
copyright:           "2021 Bradley Smith"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/N0822325/Haskell-Tax-Calculator#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  ASE-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ASE

tests:
  ASE-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ASE
    - HUnit
